import express from 'express'; 
import { GoodModel } from '../models/good.js';

const router = express.Router(); 

// GOOD ROUTES

// Basic petition to post a good
router.post('/', async (req, res) => {
  const merchant = new GoodModel(req.body);

  try {
    await merchant.save();
    res.status(201).send(merchant);
  } catch (error) {
    res.status(500).send(error)
  }
});

// Basic petition to get a good with his name 
router.get('/', async (req, res) => {
  try {
    const good = await GoodModel.find(req.query);
    if (good.length !== 0) {
      res.status(200).send(good);
    } else {
      res.status(404).send('No Goods found');
    }
  } catch (error) { 
    res.status(500).send(error);
  }
}); 

// Basic petition to get a good with his id generated by mongoose
router.get('/:id', async (req, res) => {
  try {
    const good = await GoodModel.findById(req.params.id)
    if (!good) {
      res.status(404).send('Good not found');
    } else {
      res.status(200).send(good);
    }
  } catch(error) {
    res.status(500).send(error)
  }
});

// Basic petition to modify good
router.patch('/', async (req, res) => {
  if (!req.query.name) {
    return res.status(400).send({
      error: 'A name must be provided in the query string',
    });
  }

  if (!req.body || Object.keys(req.body).length === 0) {
    return res.status(400).send({
      error: 'Fields to be modified have to be provided in the request body',
    });
  }

  const allowedUpdates = ['name', 'description', 'material', 'weight', 'crownValue', 'stock'];
  const actualUpdates = Object.keys(req.body);
  const isValidUpdate = actualUpdates.every((update) => allowedUpdates.includes(update));

  if (!isValidUpdate) {
    return res.status(400).send({
      error: 'Update is not permitted',
    });
  }

  try {
    const good = await GoodModel.findOneAndUpdate(
      { name: req.query.name.toString() },
      req.body,
      {
        new: true,
        runValidators: true,
      }
    );

    if (!good) {
      return res.status(404).send('Good not found');
    }

    res.status(200).send(good);
  } catch (error) {
    res.status(500).send({ error: error.message });
  }
});

// Basic petition to modify good
router.patch('/:id', async (req, res) => {
  if (!req.body) {
    res.status(400).send({
      error: 'Fields to be modified have to be provided in the request body',
    });
  } else {
    const allowedUpdates = ['name', 'description', 'material', 'weight', 'crownValue'];
    const actualUpdates = Object.keys(req.body);
    const isValidUpdate =
      actualUpdates.every((update) => allowedUpdates.includes(update));

    if (!isValidUpdate) {
      res.status(400).send({
        error: 'Update is not permitted',
      });
    } else {
      try {
        const good = await GoodModel.findByIdAndUpdate(req.params.id, req.body, {
            new: true,
            runValidators: true,
          })
        
        if (!GeolocationCoordinates) {
          res.status(404).send('Good not found');
        } else {
          res.status(200).send(good)
        }
      } catch(error) {
        res.status(500).send(error);
      }
    }
  }
});

// Basic delete petition to delete a good with his name
router.delete('/', async (req, res) => {
  if (!req.query.name) {
    res.status(400).send({
      error: 'A title must be provided',
    });
  } else {
    try {
      const good = await GoodModel.findOneAndDelete({name: req.query.name.toString()})
      if (!good) {
        res.status(404).send('Good not found');
      } else {
        res.status(200).send(good);
      }
    } catch(error) {
      res.status(500).send(error);
    }
  }
});

// Basic deletion petition to delete a good with his id generated by mongoose
router.delete('/:id', async (req, res) => {
  try {
    const good = await GoodModel.findByIdAndDelete(req.params.id);
    if (!good) {
      res.status(404).send('Good not found');
    }
  } catch(error) {
    res.status(500).send(error);
  }
});

export default router