import express from 'express'; 
import { GoodModel } from '../models/good.js';

const router = express.Router(); 

// MERCHANT ROUTES

// Basic petition to post a merchant
router.post('/', async (req, res) => {
  const merchant = new GoodModel(req.body);

  try {
    await merchant.save();
    res.status(201).send(merchant);
  } catch (error) {
    res.status(500).send(error)
  }
});

// Basic petition to get a merchant with his name 
router.get('/', async (req, res) => {
  const filter = req.query.name?{name: req.query.name.toString()}:{}; ;

  try {
    const merchant = await GoodModel.find(filter);
    if (merchant.length !== 0) {
      res.status(200).send(merchant);
    } else {
      res.status(404).send('No Goods found');
    }
  } catch (error) { 
    res.status(500).send(error);
  }
}); 

// Basic petition to get a merchant with his id generated by mongoose
router.get('/:id', async (req, res) => {
  try {
    const merchant = GoodModel.findById(req.params.id)
    if (!merchant) {
      res.status(404).send('Good not found');
    } else {
      res.status(200).send(merchant);
    }
  } catch(error) {
    res.status(500).send(error)
  }
});

// Basic petition to modify merchant
router.patch('/', async (req, res) => {
  if (!req.query.title) {
    res.status(400).send({
      error: 'A title must be provided in the query string',
    });
  } else if (!req.body) {
    res.status(400).send({
      error: 'Fields to be modified have to be provided in the request body',
    });
  } else {
    const allowedUpdates = ['name', 'description', 'material', 'weight', 'crownValue'];
    const actualUpdates = Object.keys(req.body);
    const isValidUpdate =
      actualUpdates.every((update) => allowedUpdates.includes(update));

    if (!isValidUpdate) {
      res.status(400).send({
        error: 'Update is not permitted',
      });
    } else {
      try {
        const merchant = await GoodModel.findOneAndUpdate({title: req.query.title.toString()}, req.body, {
            new: true,
            runValidators: true,
          })
        
        if (!merchant) {
          res.status(404).send('Good not found');
        } else {
          res.status(200).send(merchant)
        }
      } catch(error) {
        res.status(500).send(error);
      }
    }
  }
});

// Basic delete petition to delete a merchant with his name
router.delete('/', async (req, res) => {
  if (!req.query.title) {
    res.status(400).send({
      error: 'A title must be provided',
    });
  } else {
    try {
      const merchant = await GoodModel.findOneAndDelete({title: req.query.title.toString()})
      if (!merchant) {
        res.status(404).send('Good not found');
      } else {
        res.status(200).send(merchant);
      }
    } catch(error) {
      res.status(500).send(error);
    }
  }
});

// Basic deletion petition to delete a merchant with his id generated by mongoose
router.delete('/:id', async (req, res) => {
  try {
    const merchant = await GoodModel.findByIdAndDelete(req.params.id);
    if (!merchant) {
      res.status(404).send('Good not found');
    }
  } catch(error) {
    res.status(500).send(error);
  }
});

export default router