import express from 'express'; 
import { HunterModel } from '../models/hunter.js';

const router = express.Router(); 

// HUNTER ROUTES 

// Basic petition to post a hunter
router.post('/', async (req, res) => {
  const hunter = new HunterModel(req.body);

  try {
    await hunter.save();
    res.status(201).send(hunter);
  } catch (error) {
    res.status(500).send(error);
  }
}); 

// Basic petition to get a hunter with his name 
router.get('/', async (req, res) => {
  const filter = req.query.name?{name: req.query.name.toString()}:{}; ;

  try {
    const hunter = await HunterModel.find(filter);
    if (hunter.length !== 0) {
      res.status(200).send(hunter);
    } else {
      res.status(404).send('No hunters found');
    }
  } catch (error) { 
    res.status(500).send(error);
  }
}); 

// Basic petition to get a hunter with his id generated by mongoose
router.get('/:id', async (req, res) => {
  try {
    const hunter = await HunterModel.findById(req.params.id)
    if (!hunter) {
      res.status(404).send('Hunter not found');
    } else {
      res.status(200).send(hunter);
    }
  } catch(error) {
    res.status(400).send(error)
  }
});

// Basic petition to modify hunter
router.patch('/', async (req, res) => {
  if (!req.query.title) {
    res.status(400).send({
      error: 'A title must be provided in the query string',
    });
  } else if (!req.body) {
    res.status(400).send({
      error: 'Fields to be modified have to be provided in the request body',
    });
  } else {
    const allowedUpdates = ['name', 'race', 'location'];
    const actualUpdates = Object.keys(req.body);
    const isValidUpdate =
      actualUpdates.every((update) => allowedUpdates.includes(update));

    if (!isValidUpdate) {
      res.status(400).send({
        error: 'Update is not permitted',
      });
    } else {
      try {
        const hunter = await HunterModel.findOneAndUpdate({title: req.query.title.toString()}, req.body, {
            new: true,
            runValidators: true,
          })
        
        if (!hunter) {
          res.status(404).send('Hunter not found');
        } else {
          res.status(200).send(hunter)
        }
      } catch(error) {
        res.status(500).send(error);
      }
    }
  }
});

// Basic delete petition to delete a hunter with his name
router.delete('/', async (req, res) => {
  if (!req.query.title) {
    res.status(400).send({
      error: 'A title must be provided',
    });
  } else {
    try {
      const hunter = await HunterModel.findOneAndDelete({title: req.query.title.toString()})
      if (!hunter) {
        res.status(404).send('Hunter not found');
      } else {
        res.status(200).send(hunter);
      }
    } catch(error) {
      res.status(500).send(error);
    }
  }
});

// Basic deletion petition to delete a hunter with his id generated by mongoose
router.delete('/:id', async (req, res) => {
  try {
    const hunter = await HunterModel.findByIdAndDelete(req.params.id);
    if (!hunter) {
      res.status(404).send('Hunter not found');
    } else {
      res.status(200).send(hunter); 
    }
  } catch(error) {
    res.status(500).send(error);
  }
});

export default router;